version: '3.9'

services:
  redis:
    image: redis
    restart: always
    container_name: 'diary_app_redis'
    #command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'diary_app_django'
    command: bash -c "python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000" #python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
  celery:
    build:
      context: ./
    container_name: 'diary_app_celery'
    command: celery --workdir=./ -A diary_project worker --loglevel=info
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
  celery-flower:
    build: .
    #restart: always
    command: celery -A diary_project flower --loglevel=DEBUG --port=5555
    ports:
      - "127.0.0.1:5555:5555"
    #env_file:
    #  - .env
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis