# Generated by Django 4.0.4 on 2022-05-31 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diary.school', verbose_name='Номер школы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.schoolclass', verbose_name='Номер класса'),
        ),
    ]
