# Generated by Django 4.0.4 on 2022-05-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diary.school'),
        ),
    ]
