# Generated by Django 4.0.5 on 2022-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='eng_name',
            field=models.CharField(default='math', max_length=100, verbose_name='Англ сокращение предмета'),
        ),
    ]
